logging:
  level:
    root: debug
server:
  port: 8070
  servlet:
    session:
      timeout: 36000000
spring:
  profiles:
    active: develop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/${tenant-id}/
